{% set version = "0.1.2" %}

package:
  name: plaid
  version: {{ version }}

source:
  url: https://github.com/PLAID-lib/plaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 59325da2f05d1a290b6ba749ab4519b68739c6d9cdc19322e823ddee525291dc

build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<311 or py>312]
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - pip

  run:
    - python
    - tqdm
    - pyyaml
    - pycgns-core
    - numpy
    - matplotlib-base
    - scikit-learn
    - pydantic
    - datasets >=3.0

test:
  requires:
    - pytest
    - muscat ==2.4.1
  imports:
    - plaid
  source_files:
    - tests
    - examples
  commands:
    - python -m pytest tests
    - cd examples
    - bash run_examples.sh  # [unix]
    - run_examples.bat      # [win]

about:
  home: https://github.com/PLAID-lib/plaid
  summary: 'Physics Learning AI Datamodel (PLAID)'
  description: |
    A package that implements a data model tailored for AI and ML in the context of physics problems

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://plaid-lib.readthedocs.io
  dev_url: https://github.com/PLAID-lib/plaid

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
