{% set version = "0.0.7" %}

package:
  name: plaid
  version: {{ version }}

source:
  url: https://gitlab.com/drti/plaid/-/archive/{{ version }}/plaid-{{ version }}.tar.gz
  sha256: 7ea7e85e4cd53fa2282f0c6e4a24ff7a9b362fc408c042ce905d607cca21080d


build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-scm
    - pip

  run:
    - python >=3.11
    - tqdm
    - pyyaml
    - pycgns
    - numpy
    - muscat >=2.0.0
    - scikit-learn

test:
  requires:
    - pytest
    - scikit-learn
  imports:
    - plaid
  source_files:
    - tests
    - examples
  commands:
    - python -m pytest tests
    - cd examples
    - bash run_examples.sh

about:
  home: https://gitlab.com/drti/plaid
  summary: 'Physics Learning AI Datamodel (PLAID)'
  description: |
    A package that implements a data model tailored for AI and ML in the context of physics problems

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://plaid-lib.readthedocs.io
  dev_url: https://gitlab.com/drti/plaid

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
